### ISSUE TITLE
AuthApi

### ISSUE THREAD

**Issue by MIDmos** [LifeFeelDev/LifeFeelAPI#1]
Надо добавить id пользователя к ответу

**Comment by AppLoidx** [comment]
Такой сойдет?
```
curl -X GET "http://localhost:8080/v1/api/user.auth" -H "accept: */*" -H "Content-Type: application/json" -d "{ \"login\": \"test\", \"password\": \"testtesttest\", \"version\": \"1.0\"}"
```

Ответ:
```
{"username":"test", "token":"dGVzdFdlZCBEZWMgMjUgMTY6MjA6NDkgTVNLIDIwMTk=", "id":1}
```

**Comment by AppLoidx** [comment]
Я еще не прудсмотрел, если токен будет передаваться в качестве параметра, т.к. он устанавливается в куках с именем session

То есть уже после авторизации в куках будет
session=dGVzdFdlZCBEZWMgMjUgMTY6MjA6NDkgTVNLIDIwMTk=

**Comment by AppLoidx** [comment]
Если давать возможность быть установленным через параметры запроса, то на это нужно еще доп время

**Comment by AppLoidx** [comment]
https://github.com/LifeFeelDev/LifeFeelAPI/commit/3fb398dc30c8f2bc3b7d9fa84f0ce46be13ec0da
