### ISSUE TITLE
Sending messages

### ISSUE THREAD

**Issue by MIDmos** [LifeFeelDev/LifeFeelAPI#4]
/v1/api/chat.messages PUT

Выдает
{"timestamp":"2019-12-25T20:54:57.826+0000","status":500,"error":"Internal Server Error","message":"org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.lifefeel.api.entity.chat.Message; nested exception is java.lang.IllegalStateException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: com.lifefeel.api.entity.chat.Message","path":"/v1/api/chat.messages"}

**Comment by MIDmos** [comment]
fixed with
public class Chat {
    @Id
    @GeneratedValue
    private Long id;

    @ManyToMany
    private Set<User> users = new HashSet<>();

    @OneToMany(cascade = CascadeType.ALL)
    private List<Message> messages = new LinkedList<>();

    public void addUser(User u){
        users.add(u);
    }

    public void addMessage(Message msg){
        messages.add(msg);
    }

}

**Comment by AppLoidx** [comment]
Это вроде должно фикситься через Cascade

**Comment by AppLoidx** [comment]
Как-то вот так
```
    @OneToMany(cascade = CascadeType.ALL)
    private List<Message> messages = new LinkedList<>();
```

**Comment by AppLoidx** [comment]
Пофиксил это здесь https://github.com/LifeFeelDev/LifeFeelAPI/commit/18cc79cfbde0e7dea69c6bd1750117a565bc51a5

**Comment by AppLoidx** [comment]
И еще там баг был со StackOverflow. Там я добавил новую модель, так что сейчас все ок.
Попробовал создать чат и отправить сообщение, все работает

**Comment by AppLoidx** [comment]
Главное, не забыть предоставить куки с session
