### ISSUE TITLE
Loading messages

### ISSUE THREAD

**Issue by MIDmos** [LifeFeelDev/LifeFeelAPI#5]
/v1/api/chat.messages GET
 
Мб это из-за того, что я фиксил в Chat:
@OneToMany(cascade = CascadeType.ALL)
    private List<Message> messages = new LinkedList<>();

Ответ:
 {"messages":[{"id":7,"from":{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos.mos","session":"bW9zVGh1IERlYyAyNiAwMDoxNDoyMiBNU0sgMjAxOQ==","chats":[{"id":4,"users":[{"id":1,"username":"mos","password":"$1$nYei1s02$kyVujAfe8nBSOwv6EB1QR.","email":"mos@mos

**Comment by AppLoidx** [comment]
А, окей. Ну, кроч, там сериализует пользователя полностью, поэтому ошибки есть. Сейчас добавил  новую модель, где приходит только id пользователя

Например,
```json
{"messages":[{"text":"kek","from":1,"creationDate":null,"id":3}]}
```

**Comment by AppLoidx** [comment]
https://github.com/LifeFeelDev/LifeFeelAPI/commit/68de52b647aca80e01ca91b0fbd7a675f94bfa83
